use_frameworks!

target 'UITextField-Navigation_Example' do
  pod 'UITextField-Navigation', :path => '../'

  target 'UITextField-Navigation_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
