platform :ios, '9.0'
use_frameworks!

target 'UITextField-Navigation_Example' do
  pod 'UITextField-Navigation', :path => '../'
end

target 'UITextField_Navigation_Tests' do
    pod 'UITextField-Navigation', :path => '../'

    pod 'Quick', '2.0.0'
end
